# Generated by Django 5.0.6 on 2024-10-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullaniciad', models.CharField(max_length=12)),
                ('mesaj', models.CharField(max_length=350)),
            ],
        ),
    ]
